CREATE DATABASE Country

CREATE TABLE City
(
    ID          INT IDENTITY PRIMARY KEY,
    NAME        VARCHAR(17) NOT NULL,
    COUNTRYCODE VARCHAR(3)  NOT NULL,
    DISTRICT    VARCHAR(20) NOT NULL,
    POPULATION  INT         NOT NULL
)

SELECT *
    FROM City
    WHERE POPULATION >= 100000
      AND COUNTRYCODE = 'USA'